### ISSUE TITLE
Font awesome cdnjs-fa

### ISSUE THREAD

**Issue by cgiovanii** [idleberg/sublime-icon-fonts#15]
Hi!  you must to update de cdnjs-fa to new cdn link:

`<script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>`

because this are include the old version 4.7.0  and de snippets fas/far/fab does not work properly

Thank you for a awesome sublime plugin!

Cheers

**Comment by idleberg** [comment]
It's a known issue, thanks for reporting.
