### ISSUE TITLE
Ionic fonts is rendered in wrong syntax

### ISSUE THREAD

**Issue by anoop-ananthan** [idleberg/sublime-icon-fonts#8]
When a selection is made from the intellisence, eg `ion-key`, then `< class="ion-key"><//i>` is rendered on the text instead of `<i class="ion-key"></i>`.

This is a great package and I love it and Thanks!

**Comment by idleberg** [comment]
Thank you! Fixed in v3.2.3

**Comment by anoop-ananthan** [comment]
Thank you, that was fast. But now it's rendered as:
`<i class="ion-at"><//i>`

The double slash at the end remains.
